### ISSUE TITLE
expectElement is not defined.

### ISSUE THREAD

**Issue by jcope2013** [201-created/ember-cli-acceptance-test-helpers#28]
when firing up a new app with ``` ember-cli": "2.3.0-beta.2"  "ember": "2.3.0" ``

```
 ReferenceError: expectElement is not defined
    at tests.js:286
    at andThen (vendor.js:72476)
    at vendor.js:73183
    at isolate (vendor.js:73384)
    at vendor.js:73368
    at tryCatch (vendor.js:85803)
    at invokeCallback (vendor.js:85818)
    at publish (vendor.js:85786)
    at vendor.js:64297
    at Queue.invokeWithOnError (vendor.js:32039) 
```

**Comment by backspace** [comment]
I just tried it with a fresh application and it worked for me, @jcope2013. Did you follow the [Setup steps in the README](https://github.com/201-created/ember-cli-acceptance-test-helpers#setup)? Once I added `registerAcceptanceTestHelpers();`, the error went away.

**Comment by jcope2013** [comment]
yeah seemed to be the ordering of where I put that after ```  application.injectTestHelpers(); ``` would cause occasional failures, moving it above fixed it

thanks
